class ChapterMetadataItem {
  final int chapterNumber;
  final int versesCount;
  final String nameHindi;
  final String nameGujarati;
  final String nameEnglish;
  final String transliteration;
  final String meaningEnglish;
  final String meaningHindi;
  final String meaningGujarati;
  final String summaryEnglish;
  final String summaryHindi;
  final String summaryGujarati;

  const ChapterMetadataItem({
    required this.chapterNumber,
    required this.versesCount,
    required this.nameHindi,
    required this.nameGujarati,
    required this.nameEnglish,
    required this.transliteration,
    required this.meaningEnglish,
    required this.meaningHindi,
    required this.meaningGujarati,
    required this.summaryEnglish,
    required this.summaryHindi,
    required this.summaryGujarati,
  });
}

class ChapterMetadata {
  static const List<ChapterMetadataItem> chapters = [
    ChapterMetadataItem(
      chapterNumber: 1,
      versesCount: 47,
      nameHindi: 'अर्जुनविषादयोग',
      nameGujarati: 'અર્જુનવિષાદયોગ',
      nameEnglish: 'Arjuna Vishada Yoga',
      transliteration: 'Arjuna Viṣāda Yoga',
      meaningEnglish: "Arjuna's Dilemma and Despair",
      meaningHindi: 'अर्जुन का विषाद और मोह',
      meaningGujarati: 'અર્જુનનો શોક અને મોહ',
      summaryEnglish: 'On the sacred battlefield of Kurukshetra, Arjuna sees his relatives, revered elders, and teachers assembled for war. Overwhelmed by grief and moral dilemma, he casts down his bow and refuses to fight.',
      summaryHindi: 'कुरुक्षेत्र की युद्धभूमि में दोनों पक्षों के संबंधियों और गुरुजनों को देखकर अर्जुन विषादग्रस्त होकर धनुष-बाण त्याग देते हैं और भगवान श्रीकृष्ण की शरण लेते हैं।',
      summaryGujarati: 'કુરુક્ષેત્રની યુદ્ધભૂમિ પર બંને પક્ષના સ્વજનો અને ગુરુજનોને જોઈ અર્જુન શોકગ્રસ્ત થઈ ધનુષ-બાણ ત્યજી દે છે અને ભગવાન શ્રીકૃષ્ણના શરણે જાય છે.',
    ),
    ChapterMetadataItem(
      chapterNumber: 2,
      versesCount: 72,
      nameHindi: 'सांख्ययोग',
      nameGujarati: 'સાંખ્યયોગ',
      nameEnglish: 'Sankhya Yoga',
      transliteration: 'Sāṅkhya Yoga',
      meaningEnglish: 'Transcendental Knowledge & Soul',
      meaningHindi: 'गीता का सार और आत्मज्ञान',
      meaningGujarati: 'ગીતાનો સાર અને આત્મજ્ઞાન',
      summaryEnglish: 'Lord Krishna teaches the eternal nature of the soul (Atman), the illusion of death, the duty of a Kshatriya (Svadharma), and the qualities of a person of steady intellect (Sthitaprajna).',
      summaryHindi: 'श्रीकृष्ण आत्मा की अमरता, कर्मयोग का सिद्धांत और स्थितप्रज्ञ पुरुष के लक्षणों का विस्तृत वर्णन करते हैं।',
      summaryGujarati: 'શ્રીકૃષ્ણ આત્માની અમરતા, કર્મયોગનો સિદ્ધાંત અને સ્થિતપ્રજ્ઞ પુરુષના લક્ષણોનું વિસ્તૃત વર્ણન કરે છે.',
    ),
    ChapterMetadataItem(
      chapterNumber: 3,
      versesCount: 43,
      nameHindi: 'कर्मयोग',
      nameGujarati: 'કર્મયોગ',
      nameEnglish: 'Karma Yoga',
      transliteration: 'Karma Yoga',
      meaningEnglish: 'Path of Selfless Action',
      meaningHindi: 'निःस्वार्थ कर्म का मार्ग',
      meaningGujarati: 'નિષ્કામ કર્મનો માર્ગ',
      summaryEnglish: 'Krishna elucidates why action without attachment to the fruits (Nishkama Karma) is essential for inner purity and worldly harmony (Lokasangraha).',
      summaryHindi: 'भगवान श्रीकृष्ण निष्काम कर्म के महत्व और कर्तव्य पालन द्वारा आत्मशुद्धि का मार्ग बतलाते हैं।',
      summaryGujarati: 'ભગવાન શ્રીકૃષ્ણ ફળની આશા વિના નિષ્કામ કર્મ કરવાનું મહત્વ અને કર્તવ્ય પાલન દ્વારા ચિત્તશુદ્ધિનો માર્ગ બતાવે છે.',
    ),
    ChapterMetadataItem(
      chapterNumber: 4,
      versesCount: 42,
      nameHindi: 'ज्ञानकर्मसंन्यासयोग',
      nameGujarati: 'જ્ઞાનકર્મસંન્યાસયોગ',
      nameEnglish: 'Jnana Karma Sanyasa Yoga',
      transliteration: 'Jñāna Karma Sannyāsa Yoga',
      meaningEnglish: 'Wisdom in Action & Renunciation',
      meaningHindi: 'ज्ञान और कर्म संन्यास का समन्वय',
      meaningGujarati: 'જ્ઞાન અને કર્મ સંન્યાસનો સમન્વય',
      summaryEnglish: 'Krishna explains the lineage of eternal wisdom, divine incarnations (Avatara), the fourfold social order, and how spiritual knowledge consumes the bondage of karmas.',
      summaryHindi: 'अवतार के रहस्य, यज्ञ के विभिन्न प्रकार और दिव्य ज्ञान की महिमा का वर्णन किया गया है।',
      summaryGujarati: 'અવતારનું રહસ્ય, યજ્ઞના વિવિધ પ્રકાર અને દિવ્ય જ્ઞાનની મહિમાનું વર્ણન કરવામાં આવ્યું છે.',
    ),
    ChapterMetadataItem(
      chapterNumber: 5,
      versesCount: 29,
      nameHindi: 'कर्मसंन्यासयोग',
      nameGujarati: 'કર્મસંન્યાસયોગ',
      nameEnglish: 'Karma Sanyasa Yoga',
      transliteration: 'Karma Sannyāsa Yoga',
      meaningEnglish: 'Action and Renunciation',
      meaningHindi: 'संन्यास और कर्मयोग की एकता',
      meaningGujarati: 'સંન્યાસ અને કર્મયોગની એકતા',
      summaryEnglish: 'Krishna harmonizes true inner renunciation with external duty, revealing that one who acts without ego and dedicates all actions to the Supreme attains everlasting peace.',
      summaryHindi: 'कर्मसंन्यास और कर्मयोग दोनों का एक ही लक्ष्य है—यह समझाते हुए श्रीकृष्ण अंतःकरण की समता का उपदेश देते हैं।',
      summaryGujarati: 'કર્મસંન્યાસ અને કર્મયોગ બંનેનું એક જ ધ્યેય છે—તે સમજાવતાં શ્રીકૃષ્ણ અંતઃકરણની સમતાનો ઉપદેશ આપે છે.',
    ),
    ChapterMetadataItem(
      chapterNumber: 6,
      versesCount: 47,
      nameHindi: 'आत्मसंयमयोग',
      nameGujarati: 'આત્મસંયમયોગ (ધ્યાનયોગ)',
      nameEnglish: 'Dhyana Yoga',
      transliteration: 'Ātmasamyama Yoga',
      meaningEnglish: 'The Science of Meditation',
      meaningHindi: 'ध्यान और आत्मसंयम',
      meaningGujarati: 'ધ્યાન અને આત્મસંયમ',
      summaryEnglish: 'Krishna explains the path of meditation (Dhyana), how to master the restless mind through practice (Abhyasa) and detachment (Vairagya), and assures the destiny of a striving yogi.',
      summaryHindi: 'मन को वश में करने की विधि, ध्यान के नियम और योगभ्रष्ट साधक के कल्याण का आश्वासन दिया गया है।',
      summaryGujarati: 'મનને વશ કરવાની વિધિ, ધ્યાનના નિયમો અને યોગભ્રષ્ટ સાધકના કલ્યાણની ખાતરી આપવામાં આવી છે.',
    ),
    ChapterMetadataItem(
      chapterNumber: 7,
      versesCount: 30,
      nameHindi: 'ज्ञानविज्ञानयोग',
      nameGujarati: 'જ્ઞાનવિજ્ઞાનયોગ',
      nameEnglish: 'Jnana Vijnana Yoga',
      transliteration: 'Jñāna Vijñāna Yoga',
      meaningEnglish: 'Knowledge and Realization',
      meaningHindi: 'ज्ञान और परमतत्व का अनुभव',
      meaningGujarati: 'જ્ઞાન અને પરમતત્વનો અનુભવ',
      summaryEnglish: 'Krishna discloses His lower (material) and higher (spiritual) nature, the four types of devotees, and how devotion leads beyond the veils of Maya.',
      summaryHindi: 'प्रकृति के दो रूपों (अपरा और परा), माया के प्रभाव और चार प्रकार के भक्तों (आर्त, जिज्ञासु, अर्थार्थी, ज्ञानी) का वर्णन है।',
      summaryGujarati: 'પ્રકૃતિના બે સ્વરૂપો (અપરા અને પરા), માયાનો પ્રભાવ અને ચાર પ્રકારના ભક્તોનું વર્ણન છે.',
    ),
    ChapterMetadataItem(
      chapterNumber: 8,
      versesCount: 28,
      nameHindi: 'अक्षरब्रह्मयोग',
      nameGujarati: 'અક્ષરબ્રહ્મયોગ',
      nameEnglish: 'Akshara Brahma Yoga',
      transliteration: 'Akṣara Brahma Yoga',
      meaningEnglish: 'The Imperishable Absolute',
      meaningHindi: 'अविनाशी परब्रह्म का मार्ग',
      meaningGujarati: 'અવિનાશી પરબ્રહ્મનો માર્ગ',
      summaryEnglish: 'Krishna explains the cosmic cycles of creation and dissolution, the importance of remembering God at the time of passing, and the supreme imperishable realm.',
      summaryHindi: 'अंतकाल में ईश्वर स्मरण का फल, ब्रह्माण्ड की उत्पत्ति-प्रलय और मोक्ष मार्ग का रहस्य उजागर होता है।',
      summaryGujarati: 'અંતકાળે ઈશ્વર સ્મરણનું ફળ, બ્રહ્માંડની ઉત્પત્તિ-પ્રલય અને મોક્ષ માર્ગનું રહસ્ય પ્રગટ થાય છે.',
    ),
    ChapterMetadataItem(
      chapterNumber: 9,
      versesCount: 34,
      nameHindi: 'राजविद्याराजगुह्ययोग',
      nameGujarati: 'રાજવિદ્યારાજગુહ્યયોગ',
      nameEnglish: 'Raja Vidya Raja Guhya Yoga',
      transliteration: 'Rājavidyā Rājaguhya Yoga',
      meaningEnglish: 'Sovereign Science & Secret',
      meaningHindi: 'परम गोपनीय दिव्य ज्ञान',
      meaningGujarati: 'પરમ ગુપ્ત દિવ્ય જ્ઞાન',
      summaryEnglish: 'The King of Sciences is revealed: Krishna shows how even a leaf, flower, fruit, or water offered with pure devotion is received by Him, promising eternal protection to His devotees.',
      summaryHindi: 'पत्रं पुष्पं फलं तोयं—सच्ची भक्ति की शक्ति और भगवान द्वारा भक्तों के योगक्षेम के वहन का आश्वासन।',
      summaryGujarati: 'પત્રં પુષ્પં ફલં તોયં—સાચી ભક્તિની શક્તિ અને પ્રભુ દ્વારા ભક્તોના યોગક્ષેમ વહનનું વચન.',
    ),
    ChapterMetadataItem(
      chapterNumber: 10,
      versesCount: 42,
      nameHindi: 'विभूतियोग',
      nameGujarati: 'વિભૂતિયોગ',
      nameEnglish: 'Vibhuti Yoga',
      transliteration: 'Vibhūti Yoga',
      meaningEnglish: 'Divine Glories of the Lord',
      meaningHindi: 'भगवान की दिव्य विभूतियाँ',
      meaningGujarati: 'ભગવાનની દિવ્ય વિભૂતિઓ',
      summaryEnglish: 'Krishna describes His omnipresent manifestations across all beings, planets, arts, seasons, and warriors, showing that everything splendid is but a spark of His splendor.',
      summaryHindi: 'समस्त चराचर जगत में व्याप्त भगवान के दिव्य ऐश्वर्य और विभूतियों का भव्य दर्शन।',
      summaryGujarati: 'સમગ્ર ચરાચર સૃષ્ટિમાં વ્યાપ્ત ભગવાનના દિવ્ય ઐશ્વર્ય અને વિભૂતિઓનું ભવ્ય દર્શન.',
    ),
    ChapterMetadataItem(
      chapterNumber: 11,
      versesCount: 55,
      nameHindi: 'विश्वरूपदर्शनयोग',
      nameGujarati: 'વિશ્વરૂપદર્શનયોગ',
      nameEnglish: 'Vishwarupa Darshana Yoga',
      transliteration: 'Viśvarūpa Darśana Yoga',
      meaningEnglish: 'The Universal Cosmic Form',
      meaningHindi: 'भगवान का विराट विश्वरूप',
      meaningGujarati: 'ભગવાનનું વિરાટ વિશ્વરૂપ',
      summaryEnglish: 'Krishna grants Arjuna divine vision (Divya Chakshu) to witness His all-encompassing Cosmic Form containing all universes, gods, time, and cosmic destruction.',
      summaryHindi: 'दिव्य दृष्टि द्वारा अर्जुन को भगवान के अनंत, तेजोमय और कालरूपी विराट स्वरूप का साक्षात्कार होता है।',
      summaryGujarati: 'દિવ્ય દૃષ્ટિ દ્વારા અર્જુનને ભગવાનના અનંત, તેજોમય અને કાળસ્વરૂપ વિરાટ દર્શનનો સાક્ષાત્કાર થાય છે.',
    ),
    ChapterMetadataItem(
      chapterNumber: 12,
      versesCount: 20,
      nameHindi: 'भक्तियोग',
      nameGujarati: 'ભક્તિયોગ',
      nameEnglish: 'Bhakti Yoga',
      transliteration: 'Bhakti Yoga',
      meaningEnglish: 'The Path of Divine Devotion',
      meaningHindi: 'अनन्य प्रेम और भक्ति',
      meaningGujarati: 'અનન્ય પ્રેમ અને ભક્તિ',
      summaryEnglish: 'Krishna compares devotion to the Formless Absolute with loving devotion to the Personal Divine, describing the compassionate qualities dearest to Him.',
      summaryHindi: 'सगुण और निर्गुण उपासना की तुलना तथा भगवान के अति प्रिय भक्त के सद्गुणों का मनोहर वर्णन।',
      summaryGujarati: 'સગુણ અને નિર્ગુણ ઉપાસનાની તુલના તેમજ ભગવાનના અતિ વહાલા ભક્તના સદ્ગુણોનું મનોહર વર્ણન.',
    ),
    ChapterMetadataItem(
      chapterNumber: 13,
      versesCount: 35,
      nameHindi: 'क्षेत्रक्षेत्रज्ञविभागयोग',
      nameGujarati: 'ક્ષેત્રક્ષેત્રજ્ઞવિભાગયોગ',
      nameEnglish: 'Kshetra Kshetragya Vibhaga Yoga',
      transliteration: 'Kṣetra Kṣetrajña Vibhāga Yoga',
      meaningEnglish: 'Field and the Knower of the Field',
      meaningHindi: 'प्रकृति और पुरुष का विवेक',
      meaningGujarati: 'પ્રકૃતિ અને પુરુષનો વિવેક',
      summaryEnglish: 'The distinction between the perishable body/nature (Kshetra) and the immortal Witness Consciousness (Kshetragya) is illuminated with pristine clarity.',
      summaryHindi: 'शरीर (क्षेत्र) और आत्मा (क्षेत्रज्ञ) के भेद तथा आत्मज्ञान के साधनों का गंभीर विश्लेषण।',
      summaryGujarati: 'શરીર (ક્ષેત્ર) અને આત્મા (ક્ષેત્રજ્ઞ) ના ભેદ તેમજ આત્મજ્ઞાનના સાધનોનું ગહન વિશ્લેષણ.',
    ),
    ChapterMetadataItem(
      chapterNumber: 14,
      versesCount: 27,
      nameHindi: 'गुणत्रयविभागयोग',
      nameGujarati: 'ગુણત્રયવિભાગયોગ',
      nameEnglish: 'Gunatraya Vibhaga Yoga',
      transliteration: 'Guṇatraya Vibhāga Yoga',
      meaningEnglish: 'The Three Modes of Nature',
      meaningHindi: 'सत्त्व, रज और तम तीनों गुण',
      meaningGujarati: 'સત્ત્વ, રજ અને તમ ત્રણેય ગુણ',
      summaryEnglish: 'Krishna analyzes the three Gunas (Sattva - purity, Rajas - passion, Tamas - inertia) that bind the embodied soul and shows how to transcend them (Gunatita).',
      summaryHindi: 'प्रकृति के तीन गुणों के बंधन, उनके प्रभाव और गुणातीत अवस्था प्राप्त करने के साधन।',
      summaryGujarati: 'પ્રકૃતિના ત્રણ ગુણોના બંધન, તેના પ્રભાવ અને ગુણાતીત અવસ્થા પ્રાપ્ત કરવાના ઉપાયો.',
    ),
    ChapterMetadataItem(
      chapterNumber: 15,
      versesCount: 20,
      nameHindi: 'पुरुषोत्तमयोग',
      nameGujarati: 'પુરુષોત્તમયોગ',
      nameEnglish: 'Purushottama Yoga',
      transliteration: 'Puruṣottama Yoga',
      meaningEnglish: 'The Supreme Divine Personality',
      meaningHindi: 'सर्वोच्च पुरुषोत्तम स्वरूप',
      meaningGujarati: 'સર્વોચ્ચ પુરુષોત્તમ સ્વરૂપ',
      summaryEnglish: 'Using the metaphor of the cosmic Ashvattha tree with roots above and branches below, Krishna reveals Himself as the Supreme Person (Purushottama) transcending both matter and souls.',
      summaryHindi: 'उलटे अश्वत्थ वृक्ष का रूपक, क्षर-अक्षर पुरुष का रहस्य और परमेश्वर के पुरुषोत्तम स्वरूप की महिमा।',
      summaryGujarati: 'ઊંધા અશ્વત્થ વૃક્ષનું રૂપક, ક્ષર-અક્ષર પુરુષનું રહસ્ય અને પરમેશ્વરના પુરુષોત્તમ સ્વરૂપની મહિમા.',
    ),
    ChapterMetadataItem(
      chapterNumber: 16,
      versesCount: 24,
      nameHindi: 'दैवासुरसम्पद्विभागयोग',
      nameGujarati: 'દૈવાસુરસંપદ્વિભાગયોગ',
      nameEnglish: 'Daivasura Sampad Vibhaga Yoga',
      transliteration: 'Daivāsura Sampad Vibhāga Yoga',
      meaningEnglish: 'Divine and Demonic Natures',
      meaningHindi: 'दैवी और आसुरी सम्पदा',
      meaningGujarati: 'દૈવી અને આસુરી સંપત્તિ',
      summaryEnglish: 'Krishna contrasts divine virtues (fearlessness, compassion, truth) with destructive tendencies (ego, arrogance, lust, anger, greed) that lead downward.',
      summaryHindi: 'मनुष्य के आत्मोद्धार के लिए दैवी गुणों के संचय और नरक के तीन द्वारों (काम, क्रोध, लोभ) से बचने की शिक्षा।',
      summaryGujarati: 'માનવના આત્મઉદ્ધાર માટે દૈવી ગુણોના સંચય અને નરકના ત્રણ દ્વારો (કામ, ક્રોધ, લોભ) થી બચવાની શીખ.',
    ),
    ChapterMetadataItem(
      chapterNumber: 17,
      versesCount: 28,
      nameHindi: 'श्रद्धात्रयविभागयोग',
      nameGujarati: 'શ્રદ્ધાત્રયવિભાગયોગ',
      nameEnglish: 'Shraddhatraya Vibhaga Yoga',
      transliteration: 'Śraddhātraya Vibhāga Yoga',
      meaningEnglish: 'Threefold Division of Faith',
      meaningHindi: 'श्रद्धा, आहार और यज्ञ के तीन रूप',
      meaningGujarati: 'શ્રદ્ધા, આહાર અને યજ્ઞના ત્રણ રૂપ',
      summaryEnglish: 'Faith, food, sacrifice (Yajna), austerity (Tapas), and charity (Dana) are classified according to the three Gunas, culminating in the sacred syllable OM TAT SAT.',
      summaryHindi: 'सात्त्विक, राजसिक और तामसिक श्रद्धा तथा \'ॐ तत् सत्\' महामंत्र की पावन महत्ता का प्रतिपादन।',
      summaryGujarati: 'સાત્ત્વિક, રાજસિક અને તામસિક શ્રદ્ધા તેમજ \'ૐ તત્ સત્\' મહામંત્રની પાવન મહિમાનું પ્રતિપાદન.',
    ),
    ChapterMetadataItem(
      chapterNumber: 18,
      versesCount: 78,
      nameHindi: 'मोक्षसंन्यासयोग',
      nameGujarati: 'મોક્ષસંન્યાસયોગ',
      nameEnglish: 'Moksha Sanyasa Yoga',
      transliteration: 'Mokṣa Sannyāsa Yoga',
      meaningEnglish: 'Liberation through Renunciation',
      meaningHindi: 'मोक्ष और पूर्ण शरणागति',
      meaningGujarati: 'મોક્ષ અને પૂર્ણ શરણાગતિ',
      summaryEnglish: 'The grand synthesis of the Bhagavad Gita: Krishna summarizes all paths, invites total surrender (Sarva-dharman parityajya mamekam sharanam vraja), and dispels all delusion.',
      summaryHindi: 'समस्त गीता का दिव्य सार, मोक्ष प्राप्ति का उपाय और भगवान श्रीकृष्ण का परम पावन शरणागति महामंत्र।',
      summaryGujarati: 'સમગ્ર ગીતાનો દિવ્ય સાર, મોક્ષ પ્રાપ્તિનો ઉપાય અને ભગવાન શ્રીકૃષ્ણનો પરમ પાવન શરણાગતિ મહામંત્ર.',
    ),
  ];

  static ChapterMetadataItem getChapter(int chapterNumber) {
    if (chapterNumber < 1 || chapterNumber > 18) {
      return chapters.first;
    }
    return chapters[chapterNumber - 1];
  }

  static int getVerseCount(int chapterNumber) {
    return getChapter(chapterNumber).versesCount;
  }
}
