class RashiInfo {
  final int id;
  final String sanskritName;
  final String hindiName;
  final String gujaratiName;
  final String shortName;
  final String englishName;
  final String zodiacParam; // Used for API Ninjas query
  final String symbol;
  final String deity;
  final String rulingPlanet;
  final String rulingPlanetGujarati;
  final String element;
  final String elementGujarati;
  final String luckyColor;
  final int luckyNumber;
  final String dateRange;
  final String mantra;
  final String characteristics;

  const RashiInfo({
    required this.id,
    required this.sanskritName,
    required this.hindiName,
    required this.gujaratiName,
    required this.shortName,
    required this.englishName,
    required this.zodiacParam,
    required this.symbol,
    required this.deity,
    required this.rulingPlanet,
    required this.rulingPlanetGujarati,
    required this.element,
    required this.elementGujarati,
    required this.luckyColor,
    required this.luckyNumber,
    required this.dateRange,
    required this.mantra,
    required this.characteristics,
  });
}

class RashiData {
  static const List<RashiInfo> rashis = [
    RashiInfo(
      id: 1,
      sanskritName: 'मेष',
      hindiName: 'मेष',
      gujaratiName: 'મેષ',
      shortName: 'મેષ',
      englishName: 'Aries',
      zodiacParam: 'aries',
      symbol: '♈',
      deity: 'Lord Kartikeya / Mangal Dev',
      rulingPlanet: 'मंगल (Mars)',
      rulingPlanetGujarati: 'મંગળ (Mars)',
      element: 'अग्नि (Fire)',
      elementGujarati: 'અગ્નિ (Fire)',
      luckyColor: 'Red, Saffron',
      luckyNumber: 9,
      dateRange: 'Mar 21 - Apr 19',
      mantra: 'ॐ क्रां क्रीं क्रौं सः भौमाय नमः',
      characteristics: 'Courageous, determined, confident, enthusiastic, optimistic, passionate.',
    ),
    RashiInfo(
      id: 2,
      sanskritName: 'वृषभ',
      hindiName: 'वृषभ',
      gujaratiName: 'વૃષભ',
      shortName: 'વૃષ',
      englishName: 'Taurus',
      zodiacParam: 'taurus',
      symbol: '♉',
      deity: 'Goddess Lakshmi / Shukra Dev',
      rulingPlanet: 'शुक्र (Venus)',
      rulingPlanetGujarati: 'શુક્ર (Venus)',
      element: 'पृथ्वी (Earth)',
      elementGujarati: 'પૃથ્વી (Earth)',
      luckyColor: 'White, Pink, Cream',
      luckyNumber: 6,
      dateRange: 'Apr 20 - May 20',
      mantra: 'ॐ द्रां द्रीं द्रौं सः शुक्राय नमः',
      characteristics: 'Reliable, patient, practical, devoted, responsible, stable, aesthetic.',
    ),
    RashiInfo(
      id: 3,
      sanskritName: 'मिथुन',
      hindiName: 'मिथुन',
      gujaratiName: 'મિથુન',
      shortName: 'મિથુન',
      englishName: 'Gemini',
      zodiacParam: 'gemini',
      symbol: '♊',
      deity: 'Lord Ganesha / Budh Dev',
      rulingPlanet: 'बुध (Mercury)',
      rulingPlanetGujarati: 'બુધ (Mercury)',
      element: 'वायु (Air)',
      elementGujarati: 'વાયુ (Air)',
      luckyColor: 'Light Green, Yellow',
      luckyNumber: 5,
      dateRange: 'May 21 - Jun 20',
      mantra: 'ॐ ब्रां ब्रीं ब्रौं सः बुधाय नमः',
      characteristics: 'Adaptable, outgoing, intelligent, curious, communicative, witty.',
    ),
    RashiInfo(
      id: 4,
      sanskritName: 'कर्क',
      hindiName: 'कर्क',
      gujaratiName: 'કર્ક',
      shortName: 'કર્ક',
      englishName: 'Cancer',
      zodiacParam: 'cancer',
      symbol: '♋',
      deity: 'Lord Shiva / Chandra Dev',
      rulingPlanet: 'चन्द्र (Moon)',
      rulingPlanetGujarati: 'ચંદ્ર (Moon)',
      element: 'जल (Water)',
      elementGujarati: 'જળ (Water)',
      luckyColor: 'Silver, White, Milky',
      luckyNumber: 2,
      dateRange: 'Jun 21 - Jul 22',
      mantra: 'ॐ श्रां श्रीं श्रौं सः चन्द्रमसे नमः',
      characteristics: 'Intuitive, sentimental, compassionate, protective, deeply caring.',
    ),
    RashiInfo(
      id: 5,
      sanskritName: 'सिंह',
      hindiName: 'सिंह',
      gujaratiName: 'સિંહ',
      shortName: 'સિંહ',
      englishName: 'Leo',
      zodiacParam: 'leo',
      symbol: '♌',
      deity: 'Lord Surya Narayan',
      rulingPlanet: 'सूर्य (Sun)',
      rulingPlanetGujarati: 'સૂર્ય (Sun)',
      element: 'अग्नि (Fire)',
      elementGujarati: 'અગ્નિ (Fire)',
      luckyColor: 'Gold, Orange, Royal Yellow',
      luckyNumber: 1,
      dateRange: 'Jul 23 - Aug 22',
      mantra: 'ॐ ह्रां ह्रीं ह्रौं सः सूर्याय नमः',
      characteristics: 'Generous, warmhearted, creative, enthusiastic, broad-minded, noble.',
    ),
    RashiInfo(
      id: 6,
      sanskritName: 'कन्या',
      hindiName: 'कन्या',
      gujaratiName: 'કન્યા',
      shortName: 'કન્યા',
      englishName: 'Virgo',
      zodiacParam: 'virgo',
      symbol: '♍',
      deity: 'Lord Vishnu / Budh Dev',
      rulingPlanet: 'बुध (Mercury)',
      rulingPlanetGujarati: 'બુધ (Mercury)',
      element: 'पृथ्वी (Earth)',
      elementGujarati: 'પૃથ્વી (Earth)',
      luckyColor: 'Green, Navy Blue',
      luckyNumber: 5,
      dateRange: 'Aug 23 - Sep 22',
      mantra: 'ॐ बुं बुधाय नमः',
      characteristics: 'Analytical, meticulous, modest, diligent, practical, observant.',
    ),
    RashiInfo(
      id: 7,
      sanskritName: 'तुला',
      hindiName: 'तुला',
      gujaratiName: 'તુલા',
      shortName: 'તુલા',
      englishName: 'Libra',
      zodiacParam: 'libra',
      symbol: '♎',
      deity: 'Goddess Mahalakshmi',
      rulingPlanet: 'शुक्र (Venus)',
      rulingPlanetGujarati: 'શુક્ર (Venus)',
      element: 'वायु (Air)',
      elementGujarati: 'વાયુ (Air)',
      luckyColor: 'Sky Blue, Rose, White',
      luckyNumber: 6,
      dateRange: 'Sep 23 - Oct 22',
      mantra: 'ॐ शुं शुक्राय नमः',
      characteristics: 'Diplomatic, gracious, fair-minded, social, peaceful, balanced.',
    ),
    RashiInfo(
      id: 8,
      sanskritName: 'वृश्चिक',
      hindiName: 'वृश्चिक',
      gujaratiName: 'વૃશ્ચિક',
      shortName: 'વૃશ્ચિક',
      englishName: 'Scorpio',
      zodiacParam: 'scorpio',
      symbol: '♏',
      deity: 'Lord Hanuman / Mangal Dev',
      rulingPlanet: 'मंगल (Mars)',
      rulingPlanetGujarati: 'મંગળ (Mars)',
      element: 'जल (Water)',
      elementGujarati: 'જળ (Water)',
      luckyColor: 'Maroon, Crimson, Rust',
      luckyNumber: 9,
      dateRange: 'Oct 23 - Nov 21',
      mantra: 'ॐ अं अंगारकाय नमः',
      characteristics: 'Resourceful, powerful, brave, passionate, stubborn, profound.',
    ),
    RashiInfo(
      id: 9,
      sanskritName: 'धनु',
      hindiName: 'धनु',
      gujaratiName: 'ધનુ',
      shortName: 'ધનુ',
      englishName: 'Sagittarius',
      zodiacParam: 'sagittarius',
      symbol: '♐',
      deity: 'Lord Dakshinamurthy / Guru Dev',
      rulingPlanet: 'बृहस्पति (Jupiter)',
      rulingPlanetGujarati: 'ગુરુ (Jupiter)',
      element: 'अग्नि (Fire)',
      elementGujarati: 'અગ્નિ (Fire)',
      luckyColor: 'Yellow, Purple, Turmeric',
      luckyNumber: 3,
      dateRange: 'Nov 22 - Dec 21',
      mantra: 'ॐ ग्रां ग्रीं ग्रौं सः गुरवे नमः',
      characteristics: 'Generous, idealistic, great sense of humor, philosophical, optimistic.',
    ),
    RashiInfo(
      id: 10,
      sanskritName: 'मकर',
      hindiName: 'मकर',
      gujaratiName: 'મકર',
      shortName: 'મકર',
      englishName: 'Capricorn',
      zodiacParam: 'capricorn',
      symbol: '♑',
      deity: 'Lord Shani / Lord Shiva',
      rulingPlanet: 'शनि (Saturn)',
      rulingPlanetGujarati: 'શનિ (Saturn)',
      element: 'पृथ्वी (Earth)',
      elementGujarati: 'પૃથ્વી (Earth)',
      luckyColor: 'Black, Dark Blue, Grey',
      luckyNumber: 8,
      dateRange: 'Dec 22 - Jan 19',
      mantra: 'ॐ प्रां प्रीं प्रौं सः शनैश्चराय नमः',
      characteristics: 'Responsible, disciplined, self-control, good managers, patient.',
    ),
    RashiInfo(
      id: 11,
      sanskritName: 'कुम्भ',
      hindiName: 'कुम्भ',
      gujaratiName: 'કુંભ',
      shortName: 'કુંભ',
      englishName: 'Aquarius',
      zodiacParam: 'aquarius',
      symbol: '♒',
      deity: 'Lord Rudra / Shani Dev',
      rulingPlanet: 'शनि (Saturn)',
      rulingPlanetGujarati: 'શનિ (Saturn)',
      element: 'वायु (Air)',
      elementGujarati: 'વાયુ (Air)',
      luckyColor: 'Electric Blue, Turquoise',
      luckyNumber: 8,
      dateRange: 'Jan 20 - Feb 18',
      mantra: 'ॐ शं शनैश्चराय नमः',
      characteristics: 'Progressive, original, independent, humanitarian, intellectual.',
    ),
    RashiInfo(
      id: 12,
      sanskritName: 'मीन',
      hindiName: 'मीन',
      gujaratiName: 'મીન',
      shortName: 'મીન',
      englishName: 'Pisces',
      zodiacParam: 'pisces',
      symbol: '♓',
      deity: 'Lord Vishnu / Guru Dev',
      rulingPlanet: 'बृहस्पति (Jupiter)',
      rulingPlanetGujarati: 'ગુરુ (Jupiter)',
      element: 'जल (Water)',
      elementGujarati: 'જળ (Water)',
      luckyColor: 'Yellow, Sea Green, Golden',
      luckyNumber: 3,
      dateRange: 'Feb 19 - Mar 20',
      mantra: 'ॐ बृं बृहस्पतये नमः',
      characteristics: 'Compassionate, artistic, intuitive, gentle, wise, deeply spiritual.',
    ),
  ];

  static RashiInfo getRashiById(int id) {
    return rashis.firstWhere((r) => r.id == id, orElse: () => rashis.first);
  }

  static RashiInfo getRashiByParam(String param) {
    return rashis.firstWhere(
      (r) => r.zodiacParam.toLowerCase() == param.toLowerCase(),
      orElse: () => rashis.first,
    );
  }
}
